# Generated by Django 4.1.5 on 2023-05-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_alter_employees_employees_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employee_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
