# Generated by Django 4.1.5 on 2023-05-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_employees_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employee_email',
            field=models.EmailField(max_length=254),
        ),
    ]
